17:18:00.789 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:19:00.120 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:20:00.123 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:21:00.216 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:22:00.117 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:23:00.120 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:24:00.127 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:25:00.142 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:26:00.128 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:27:00.108 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:28:00.116 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:29:00.138 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:30:00.128 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:31:00.749 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:32:00.172 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:33:00.132 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:34:00.105 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:35:00.121 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:36:00.132 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:37:00.121 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:38:00.127 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:39:00.137 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:40:00.132 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:41:00.112 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:42:00.134 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
17:58:10.237 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
18:14:05.863 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
18:30:03.877 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
18:56:35.642 [scheduling-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - [handleError,95] - Unexpected error occurred in scheduled task
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 567497ms.
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:305)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:574)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:361)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.smartlink.archive.task.generate.GenerateArchiveTasksService$$EnhancerBySpringCGLIB$$58c66dbc.generateArchiveTasks(<generated>)
	at com.smartlink.archive.task.GenerateArchiveTasksScheduling.running(GenerateArchiveTasksScheduling.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 567497ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:261)
	... 25 common frames omitted
Caused by: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2485)
	at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:560)
	at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:173)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
	... 28 common frames omitted
Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:761)
	at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:568)
	at com.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2481)
	... 31 common frames omitted
18:57:30.163 [scheduling-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - [handleError,95] - Unexpected error occurred in scheduled task
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30126ms.
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:305)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:574)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:361)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.smartlink.archive.task.generate.GenerateArchiveTasksService$$EnhancerBySpringCGLIB$$58c66dbc.generateArchiveTasks(<generated>)
	at com.smartlink.archive.task.GenerateArchiveTasksScheduling.running(GenerateArchiveTasksScheduling.java:27)
	at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30126ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:261)
	... 24 common frames omitted
Caused by: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2485)
	at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:560)
	at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:173)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
	... 27 common frames omitted
Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
	at sun.reflect.GeneratedConstructorAccessor37.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:761)
	at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:568)
	at com.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2481)
	... 30 common frames omitted
18:58:00.168 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
18:59:00.158 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
19:00:00.139 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
19:01:00.115 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
19:02:00.271 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
19:03:00.243 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
19:04:00.136 [scheduling-1] ERROR c.s.a.t.g.GenerateArchiveTasksService - [generateArchiveTasks,65] - [BIZ] >>>>>>>>>>>>>>>> 当前没有归档任务需要生成
19:05:30.194 [scheduling-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - [handleError,95] - Unexpected error occurred in scheduled task
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30171ms.
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:305)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:574)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:361)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.smartlink.archive.task.generate.GenerateArchiveTasksService$$EnhancerBySpringCGLIB$$58c66dbc.generateArchiveTasks(<generated>)
	at com.smartlink.archive.task.GenerateArchiveTasksScheduling.running(GenerateArchiveTasksScheduling.java:27)
	at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30171ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:261)
	... 24 common frames omitted
Caused by: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2485)
	at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:560)
	at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:173)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
	... 27 common frames omitted
Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
	at sun.reflect.GeneratedConstructorAccessor37.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:761)
	at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:568)
	at com.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2481)
	... 30 common frames omitted
19:06:03.372 [scheduling-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - [handleError,95] - Unexpected error occurred in scheduled task
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is java.sql.SQLException: HikariPool-1 - Interrupted during connection acquisition
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:305)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:574)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:361)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.smartlink.archive.task.generate.GenerateArchiveTasksService$$EnhancerBySpringCGLIB$$58c66dbc.generateArchiveTasks(<generated>)
	at com.smartlink.archive.task.GenerateArchiveTasksScheduling.running(GenerateArchiveTasksScheduling.java:27)
	at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: HikariPool-1 - Interrupted during connection acquisition
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:201)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:261)
	... 24 common frames omitted
Caused by: java.lang.InterruptedException: null
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:944)
	at com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:151)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:180)
	... 27 common frames omitted
